const data = {
  products: [
    {
      name: "Free Shirt",
      id: "free-shirt",
      category: "Shirts",
      image: "/images/shirt01.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      id: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt02.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      id: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt03.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      id: "golf-pants",
      category: "Pants",
      image: "/images/pants01.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      id: "fit-pants",
      category: "Pants",
      image: "/images/pants02.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      id: "classic-pants",
      category: "Pants",
      image: "/images/pants03.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};

export default data;
